// =============================//
// script generated by zeus 
// a Z tool
// z_arma@hotmail.com
// =============================//


// id 0;
_pos = [4306.7061, 11359.247, 0];
grp1 = createGroup (LOGIC);
_veh1 = grp1 createUnit ["Logic", _pos,[],0,"NONE"];
_veh1 setPos _pos;
_veh1 setSkill 0.60000002;


// id 
_pos = [4309.2275, 11343.394, 0];
_radius = 0;
_wp2 = grp1 addWaypoint [_pos,_radius];
_wp2 setwaypointtype "AND";
_wp2 setWaypointTimeout [120,120,120];

// id 1;
_pos = [4330.3984, 11360.274, 0];
grp2 = createGroup (LOGIC);
Objectifs = grp2 createUnit ["Logic", _pos,[],0,"NONE"];
Objectifs setPos _pos;
Objectifs setSkill 0.60000002;


// id 4;
_pos = [3590.4639, 2216.054, 0];
grp3 = createGroup (WEST);
_veh4 = grp3 createUnit ["USMC_Soldier_Pilot", _pos,[],0,"NONE"];
_veh4 setDir 102.06371;
_veh4 setPos _pos;
_veh4 setSkill 0.60000002;


// id 5;
_pos = [4676.9824, 10269.438, 0];
grp4 = createGroup (WEST);
_veh5 = grp4 createUnit ["USMC_Soldier_Officer", _pos,[],0,"NONE"];
_veh5 setDir 93.623901;
_veh5 setPos _pos;
_veh5 setSkill 0.60000002;


// id 7;
_pos = [4754.4966, 10490.678, 0];
grp5 = createGroup (LOGIC);
_veh6 = grp5 createUnit ["BIS_ARTY_Logic", _pos,[],0,"NONE"];
_veh6 setPos _pos;
_veh6 setSkill 0.60000002;


// id 8;
_pos = [4262.1509, 11384.876, 0];
grp6 = createGroup (LOGIC);
_veh7 = grp6 createUnit ["FunctionsManager", _pos,[],0,"NONE"];
_veh7 setPos _pos;
_veh7 setSkill 0.60000002;


// id 2;
_pos = [4732.4307, 10115.604, 0];
_veh8 = createVehicle ["HeliH", _pos,[],0,"NONE"];
_veh8 setDir 238.414;
_veh8 setPos _pos;
_veh8 setSkill 0.60000002;


// id 3;
_pos = [4732.6709, 10115.226, 0];
UH1 = createVehicle ["UH1Y", _pos,[],0,"NONE"];
UH1 setDir 238.414;
UH1 setPos _pos;
UH1 setSkill 0.60000002;


// id 6;
_pos = [4687.2124, 10624.462, 0];
_veh10 = createVehicle ["USMC_WarfareBArtilleryRadar", _pos,[],0,"NONE"];
_veh10 setDir 230;
_veh10 setPos _pos;
_veh10 setSkill 0.60000002;


// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 

// id 
_pos = [4359.7583, 11365.903, 0];
_t38 = createTrigger["EmptyDetector",_pos];
_t38 setTriggerArea [5,5,0,False];
_t38 setTriggerActivation ["NONE","LOOSE",True];
_t38 setTriggerTimeout [15,15,15,true];

// id 
_pos = [4349.7271, 11365.415, 0];
_t39 = createTrigger["EmptyDetector",_pos];
_t39 setTriggerArea [5,5,0,False];
_t39 setTriggerActivation ["NONE","PRESENT",True];
_t39 setTriggerTimeout [15,15,15,true];

// id 
_pos = [4300.3467, 11381.976, 0];
_t40 = createTrigger["EmptyDetector",_pos];
_t40 setTriggerArea [0,0,0,False];
_t40 setTriggerActivation ["NONE","PRESENT",True];

// id 
_pos = [4300.6924, 11392.602, 0];
_t41 = createTrigger["EmptyDetector",_pos];
_t41 setTriggerArea [0,0,0,False];
_t41 setTriggerActivation ["NONE","PRESENT",True];
_t41 setTriggerTimeout [1,1,1,False];

// id 
_pos = [3739.6404, 11808.521, 0];
_t42 = createTrigger["EmptyDetector",_pos];
_t42 setTriggerArea [0,0,0,False];
_t42 setTriggerStatements ["This","onMapSingleClick 'player setPos _pos; onMapSingleClick '''';';",];
_t42 setTriggerActivation ["CHARLIE","PRESENT",True];
_t42 setTriggerText "Map Click Teleport"

// id 
_pos = [3633.9609, 2201.3787, 0];
_t43 = createTrigger["EmptyDetector",_pos];
_t43 setTriggerArea [5,30,17.676254,True];
_t43 setTriggerStatements ["This","hint 'ok'",];
_t43 setTriggerActivation ["WEST","PRESENT",True];
